"use client";

import * as Dialog from "@radix-ui/react-dialog";
import NextImage from "next/image";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Apple, Camera, Candy, ChevronLeft, ChevronRight, Cigarette, Clock3, Edit3, ImagePlus, Plus, Sparkles, Trash2, Utensils, X } from "lucide-react";
import { useApi, apiRequest } from "@/hooks/use-api";
import { useAdmin } from "@/components/admin-gate";
import { ErrorState } from "@/components/error-state";
import { PageSkeleton } from "@/components/ui/skeleton";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { addDays, dateInTimezone, formatLongDate, formatShortDate, timeInTimezone } from "@/lib/date";
import type { DefaultMealType, FoodAnalysisResult, FoodEntry, MealType, SmokingEntry } from "@/lib/types";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { useAppSettings } from "@/components/app-settings";

type SeriesDay = { date: string; calories: number | null; meals: number; desserts: number };
type Period = { start: string; end: string; series: SeriesDay[]; total: number; average: number | null; highest: SeriesDay | null; lowest: SeriesDay | null; recordedDays: number; meals: number; desserts: number };
type CalorieData = { anchor: string; today: { entries: FoodEntry[]; byMeal: Array<{ type: MealType; calories: number }>; total: number; meals: number; desserts: number }; week: Period; month: Period; smokingEntries: SmokingEntry[] };
type AnalysisResponse = { result: FoodAnalysisResult; mode: "demo" | "openai"; notice?: string };
type EntryDraft = { id?: string; entryDate: string; entryTime: string; mealName: string; mealType: MealType; confirmedCalories: number; aiEstimatedCalories: number | null; minimumCalories: number | null; maximumCalories: number | null; foodItems: FoodAnalysisResult["foods"]; isDessert: boolean; confidence: FoodAnalysisResult["confidence"] | null; assumptions: string[] };

const inputClass = "min-h-11 w-full rounded-xl border border-line bg-[#0b0d10] px-3 text-sm text-white outline-none transition-colors focus:border-acid";
const mealLabels: Record<MealType, string> = { breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", snack: "Snack", unknown: "Other" };

function selectedMealType(setting: DefaultMealType, detected: MealType = "unknown") { return setting === "auto" ? detected : setting; }
function blankDraft(date: string, time: string, setting: DefaultMealType): EntryDraft { return { entryDate: date, entryTime: time, mealName: "", mealType: selectedMealType(setting), confirmedCalories: 0, aiEstimatedCalories: null, minimumCalories: null, maximumCalories: null, foodItems: [], isDessert: false, confidence: null, assumptions: [] }; }
function entryToDraft(entry: FoodEntry): EntryDraft { return { ...entry }; }
function analysisToDraft(result: FoodAnalysisResult, date: string, time: string, setting: DefaultMealType): EntryDraft { return { entryDate: date, entryTime: time, mealName: result.meal_name, mealType: selectedMealType(setting, result.meal_type), confirmedCalories: result.total_estimated_calories, aiEstimatedCalories: result.total_estimated_calories, minimumCalories: result.minimum_estimated_calories, maximumCalories: result.maximum_estimated_calories, foodItems: result.foods, isDessert: result.is_dessert, confidence: result.confidence, assumptions: result.assumptions }; }

async function compressImage(file: File) {
  const url = URL.createObjectURL(file);
  try {
    const image = await new Promise<HTMLImageElement>((resolve, reject) => { const element = new Image(); element.onload = () => resolve(element); element.onerror = reject; element.src = url; });
    const max = 1600; const ratio = Math.min(1, max / Math.max(image.width, image.height));
    const canvas = document.createElement("canvas"); canvas.width = Math.round(image.width * ratio); canvas.height = Math.round(image.height * ratio);
    canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/jpeg", .82);
  } finally { URL.revokeObjectURL(url); }
}

function EntryDialog({ draft, setDraft, open, onOpenChange, onSave, busy }: { draft: EntryDraft; setDraft: (draft: EntryDraft) => void; open: boolean; onOpenChange: (open: boolean) => void; onSave: () => void; busy: boolean }) {
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[70] bg-black/75 backdrop-blur-sm" /><Dialog.Content className="fixed inset-x-4 top-1/2 z-[80] mx-auto max-h-[88vh] max-w-lg -translate-y-1/2 overflow-y-auto rounded-3xl border border-line bg-panel p-5 shadow-2xl outline-none md:p-6"><div className="flex items-start justify-between"><div><Dialog.Title className="font-display text-xl font-bold">{draft.id ? "Edit meal" : "Add a meal"}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-zinc-500">Confirmed calories power all intake statistics.</Dialog.Description></div><Dialog.Close className="flex h-10 w-10 items-center justify-center rounded-xl text-zinc-500 hover:bg-white/5"><X size={18} /></Dialog.Close></div>
    <div className="mt-6 space-y-4"><label className="block"><span className="mb-1.5 block text-xs text-zinc-500">Meal name</span><input className={inputClass} value={draft.mealName} onChange={(e) => setDraft({ ...draft, mealName: e.target.value })} /></label><div className="grid grid-cols-2 gap-3"><label><span className="mb-1.5 block text-xs text-zinc-500">Date</span><input type="date" className={inputClass} value={draft.entryDate} onChange={(e) => setDraft({ ...draft, entryDate: e.target.value })} /></label><label><span className="mb-1.5 block text-xs text-zinc-500">Time</span><input type="time" className={inputClass} value={draft.entryTime} onChange={(e) => setDraft({ ...draft, entryTime: e.target.value })} /></label></div><div className="grid grid-cols-2 gap-3"><label><span className="mb-1.5 block text-xs text-zinc-500">Meal type</span><select className={inputClass} value={draft.mealType} onChange={(e) => setDraft({ ...draft, mealType: e.target.value as MealType })}>{Object.entries(mealLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="mb-1.5 block text-xs text-zinc-500">Confirmed kcal</span><input type="number" min="0" max="30000" className={inputClass} value={draft.confirmedCalories} onChange={(e) => setDraft({ ...draft, confirmedCalories: Number(e.target.value) })} /></label></div><label className="flex min-h-12 items-center justify-between rounded-xl border border-line bg-[#0b0d10] px-3 text-sm"><span><span className="block font-medium">Sweet treat</span><span className="text-xs text-zinc-600">Affects the lifecycle ledger once</span></span><input type="checkbox" checked={draft.isDessert} onChange={(e) => setDraft({ ...draft, isDessert: e.target.checked })} className="h-5 w-5 accent-[#c8ff3d]" /></label></div>
    <div className="mt-6 grid grid-cols-2 gap-3"><Button variant="secondary" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={busy || !draft.mealName.trim()} onClick={onSave}>{busy ? "Saving…" : "Save meal"}</Button></div>
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function AnalysisDialog({ open, setOpen, preview, analysis, analyzing, error, draft, setDraft, onSave, busy, onNewFile }: { open: boolean; setOpen: (open: boolean) => void; preview: string | null; analysis: AnalysisResponse | null; analyzing: boolean; error: string | null; draft: EntryDraft; setDraft: (draft: EntryDraft) => void; onSave: () => void; busy: boolean; onNewFile: (file: File) => void }) {
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[70] bg-black/80 backdrop-blur-sm" /><Dialog.Content className="fixed inset-x-3 top-1/2 z-[80] mx-auto max-h-[92vh] max-w-2xl -translate-y-1/2 overflow-y-auto rounded-3xl border border-line bg-panel p-5 shadow-2xl outline-none md:p-7"><div className="flex items-start justify-between"><div><Dialog.Title className="font-display text-xl font-bold">AI meal estimate</Dialog.Title><Dialog.Description className="mt-1 text-sm text-zinc-500">Review and change every value before anything is saved.</Dialog.Description></div><button onClick={() => setOpen(false)} className="flex h-10 w-10 items-center justify-center rounded-xl text-zinc-500 hover:bg-white/5"><X size={18} /></button></div>
    {preview && <div className="relative mt-5 h-44 overflow-hidden rounded-2xl bg-black md:h-56"><NextImage src={preview} alt="Temporary meal preview" fill unoptimized className="object-cover" /></div>}
    {analyzing && <div className="flex min-h-52 flex-col items-center justify-center text-center"><Sparkles className="mb-4 animate-pulse text-acid" /><p className="font-display text-lg font-bold">Estimating your meal…</p><p className="mt-2 max-w-sm text-sm leading-6 text-zinc-500">Looking at visible ingredients, portions and uncertainty. The image is not being stored.</p></div>}
    {error && <div className="my-5 rounded-2xl bg-coral/10 p-4 text-sm text-coral">{error}</div>}
    {analysis && !analyzing && <div className="mt-5"><div className="mb-4 flex flex-wrap items-center gap-2"><span className="rounded-full bg-acid/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-acid">{analysis.result.confidence} confidence</span><span className="rounded-full bg-white/[.05] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-zinc-400">{analysis.mode === "demo" ? "Demo estimate" : "OpenAI estimate"}</span>{analysis.result.is_dessert && <span className="rounded-full bg-coral/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-coral">Sweet treat</span>}</div><div className="grid gap-3 md:grid-cols-2"><label><span className="mb-1.5 block text-xs text-zinc-500">Meal name</span><input className={inputClass} value={draft.mealName} onChange={(e) => setDraft({ ...draft, mealName: e.target.value })} /></label><label><span className="mb-1.5 block text-xs text-zinc-500">Confirmed kcal</span><input type="number" className={inputClass} value={draft.confirmedCalories} onChange={(e) => setDraft({ ...draft, confirmedCalories: Number(e.target.value) })} /></label><label><span className="mb-1.5 block text-xs text-zinc-500">Meal type</span><select className={inputClass} value={draft.mealType} onChange={(e) => setDraft({ ...draft, mealType: e.target.value as MealType })}>{Object.entries(mealLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label><span className="mb-1.5 block text-xs text-zinc-500">Date</span><input type="date" className={inputClass} value={draft.entryDate} onChange={(e) => setDraft({ ...draft, entryDate: e.target.value })} /></label><label><span className="mb-1.5 block text-xs text-zinc-500">Time</span><input type="time" className={inputClass} value={draft.entryTime} onChange={(e) => setDraft({ ...draft, entryTime: e.target.value })} /></label></div></div>
      <div className="mt-5 grid grid-cols-3 gap-px overflow-hidden rounded-xl bg-line"><div className="bg-[#0b0d10] p-3 text-center"><p className="text-[10px] text-zinc-600">Low</p><p className="mt-1 font-semibold">{analysis.result.minimum_estimated_calories}</p></div><div className="bg-[#0b0d10] p-3 text-center"><p className="text-[10px] text-zinc-600">Estimate</p><p className="mt-1 font-semibold text-acid">{analysis.result.total_estimated_calories}</p></div><div className="bg-[#0b0d10] p-3 text-center"><p className="text-[10px] text-zinc-600">High</p><p className="mt-1 font-semibold">{analysis.result.maximum_estimated_calories}</p></div></div>
      <div className="mt-5"><p className="eyebrow">Visible items</p><div className="mt-2 divide-y divide-line rounded-xl border border-line px-3">{analysis.result.foods.map((food, index) => <div key={`${food.name}-${index}`} className="flex justify-between gap-3 py-3 text-sm"><span><span className="font-medium">{food.name}</span><span className="ml-2 text-xs text-zinc-600">{food.estimated_portion}</span></span><span>{food.estimated_calories} kcal</span></div>)}</div></div>
      <div className="mt-5 rounded-xl bg-white/[.025] p-3"><p className="eyebrow">Key assumptions</p><ul className="mt-2 space-y-1 text-xs leading-5 text-zinc-500">{analysis.result.assumptions.map((item) => <li key={item}>• {item}</li>)}</ul></div><label className="mt-4 flex min-h-12 items-center justify-between rounded-xl border border-line px-3 text-sm"><span>Mark as a sweet treat</span><input type="checkbox" checked={draft.isDessert} onChange={(e) => setDraft({ ...draft, isDessert: e.target.checked })} className="h-5 w-5 accent-[#c8ff3d]" /></label>
      <div className="mt-6 grid grid-cols-2 gap-2 md:grid-cols-4"><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><label className="inline-flex min-h-11 cursor-pointer items-center justify-center rounded-xl border border-line bg-[#171b20] px-3 text-sm font-semibold hover:bg-[#1d2228]"><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) onNewFile(file); e.currentTarget.value = ""; }} />Reanalyze</label><Button className="col-span-2" disabled={busy || !draft.mealName.trim()} onClick={onSave}>{busy ? "Saving…" : "Confirm & add"}</Button></div>
    </div>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function PeriodChart({ period, compact = false }: { period: Period; compact?: boolean }) {
  const chart = period.series.map((day) => ({ ...day, label: formatShortDate(day.date), display: day.calories }));
  return <Card className="p-4 md:p-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">{formatShortDate(period.start)} — {formatShortDate(period.end)}</p><p className="mt-2 font-display text-3xl font-bold">{period.total.toLocaleString()} <span className="text-sm text-zinc-600">kcal</span></p></div><p className="text-xs text-zinc-500">Average {period.average === null ? "—" : `${period.average} kcal`} · {period.recordedDays} days recorded</p></div><div className={compact ? "h-64" : "h-72"}><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{ left: -22, right: 4 }}><CartesianGrid stroke="#252a31" vertical={false} /><XAxis dataKey="label" stroke="#5c626c" fontSize={10} tickLine={false} axisLine={false} interval={compact ? 0 : 4} /><YAxis stroke="#5c626c" fontSize={10} tickLine={false} axisLine={false} /><Tooltip cursor={{ fill: "rgba(255,255,255,.03)" }} contentStyle={{ background: "#111418", border: "1px solid #252a31", borderRadius: 12, fontSize: 12 }} formatter={(value) => value === null ? ["Not recorded", "Intake"] : [`${value} kcal`, "Intake"]} /><Bar dataKey="display" fill="#c8ff3d" radius={[5, 5, 0, 0]} maxBarSize={compact ? 42 : 18} /></BarChart></ResponsiveContainer></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-line pt-4 text-xs md:grid-cols-4"><span><b className="text-white">{period.highest?.calories ?? "—"}</b><span className="ml-1 text-zinc-600">highest</span></span><span><b className="text-white">{period.lowest?.calories ?? "—"}</b><span className="ml-1 text-zinc-600">lowest</span></span><span><b className="text-white">{period.meals}</b><span className="ml-1 text-zinc-600">meals</span></span><span><b className="text-white">{period.desserts}</b><span className="ml-1 text-zinc-600">sweet treats</span></span></div></Card>;
}

export default function CaloriesPage() {
  const { settings, text } = useAppSettings();
  const businessToday = dateInTimezone(new Date(), settings.timezone);
  const businessTime = () => timeInTimezone(new Date(), settings.timezone);
  const [date, setDate] = useState(businessToday);
  const [view, setView] = useState<"day" | "week" | "month">("day");
  const { data, loading, error, refetch } = useApi<CalorieData>(useMemo(() => `/api/public/calories?date=${date}`, [date]));
  const { requireAdmin } = useAdmin();
  const [entryOpen, setEntryOpen] = useState(false); const [draft, setDraft] = useState<EntryDraft>(blankDraft(date, businessTime(), settings.defaultMealType)); const [saving, setSaving] = useState(false);
  const [analysisOpen, setAnalysisOpen] = useState(false); const [preview, setPreview] = useState<string | null>(null); const [analysis, setAnalysis] = useState<AnalysisResponse | null>(null); const [analyzing, setAnalyzing] = useState(false); const [analysisError, setAnalysisError] = useState<string | null>(null);

  const saveEntry = () => requireAdmin(async () => { setSaving(true); try { await apiRequest(draft.id ? "/api/food/update" : "/api/food/create", draft.id ? "PATCH" : "POST", draft); toast.success(draft.id ? "Meal updated." : "Meal added."); setEntryOpen(false); setAnalysisOpen(false); if (preview) URL.revokeObjectURL(preview); setPreview(null); await refetch(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Save failed."); } finally { setSaving(false); } });
  const beginAnalysis = (file: File) => requireAdmin(async () => {
    if (file.size > 10 * 1024 * 1024) { toast.error("Choose an image smaller than 10 MB."); return; }
    if (preview) URL.revokeObjectURL(preview); const localPreview = URL.createObjectURL(file); setPreview(localPreview); setAnalysisOpen(true); setAnalyzing(true); setAnalysis(null); setAnalysisError(null);
    try {
      const imageDataUrl = await compressImage(file);
      const result = await apiRequest<AnalysisResponse>("/api/analyze-food", "POST", { imageDataUrl });
      const analyzedDraft = analysisToDraft(result.result, dateInTimezone(new Date(), settings.timezone), businessTime(), settings.defaultMealType);
      if (settings.requireAiConfirmation) { setAnalysis(result); setDraft(analyzedDraft); }
      else {
        await apiRequest("/api/food/create", "POST", analyzedDraft);
        setAnalysisOpen(false); URL.revokeObjectURL(localPreview); setPreview(null);
        toast.success("AI result saved automatically."); await refetch();
      }
      if (result.notice) toast.info(result.notice);
    }
    catch (caught) { setAnalysisError(caught instanceof Error ? caught.message : "Analysis failed."); }
    finally { setAnalyzing(false); }
  });
  const deleteMeal = (entry: FoodEntry) => requireAdmin(async () => { if (!window.confirm(`Delete “${entry.mealName}”?`)) return; try { await apiRequest("/api/food/delete", "DELETE", { id: entry.id }); toast.success("Meal deleted and lifecycle effect reversed."); await refetch(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Delete failed."); } });
  const logSmoking = () => requireAdmin(async () => { if (!window.confirm("Record one smoking event now?")) return; try { await apiRequest("/api/smoking/create", "POST", { entryDate: dateInTimezone(new Date(), settings.timezone), entryTime: businessTime(), requestId: crypto.randomUUID() }); toast.success("Smoking event recorded."); await refetch(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Could not record event."); } });
  const deleteSmokingEntry = (entry: SmokingEntry) => requireAdmin(async () => { if (!window.confirm("Delete this smoking record and reverse its lifecycle effect?")) return; try { await apiRequest("/api/smoking/delete", "DELETE", { id: entry.id }); toast.success("Smoking record deleted."); await refetch(); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Delete failed."); } });

  if (loading) return <PageSkeleton />;
  if (error || !data) return <ErrorState message={error || "Calorie data unavailable."} retry={() => void refetch()} />;
  return <div className="page-wrap">
    <header className="mb-7 flex flex-col gap-5 md:mb-9 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow mb-3">{text("Nutrition & life log", "饮食与生活记录")}</p><h1 className="display-title">{text("Calorie Intake", "卡路里摄取")}</h1><p className="mt-3 text-sm text-zinc-500">{text("Estimates support awareness — they are never exact measurements.", "估算用于帮助了解摄取情况，并非精确测量。")}</p></div><div className={cn("grid gap-2", settings.aiFoodAnalysisEnabled ? "grid-cols-2" : "grid-cols-1")}>{settings.aiFoodAnalysisEnabled && <label className="inline-flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-xl bg-acid px-4 text-sm font-semibold text-ink"><ImagePlus size={17} /><span>{text("Analyze photo", "分析照片")}</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) void beginAnalysis(file); e.currentTarget.value = ""; }} /></label>}<Button variant="secondary" onClick={() => void requireAdmin(() => { setDraft(blankDraft(date, businessTime(), settings.defaultMealType)); setEntryOpen(true); })}><Plus size={17} />{text("Add manually", "手动添加")}</Button></div></header>

    <div className="mb-5 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="inline-grid grid-cols-3 rounded-xl border border-line bg-panel p-1">{(["day", "week", "month"] as const).map((item) => <button key={item} onClick={() => setView(item)} className={cn("min-h-10 rounded-lg px-5 text-xs font-semibold capitalize text-zinc-500", view === item && "bg-white/[.08] text-white")}>{item}</button>)}</div><div className="flex items-center justify-between gap-2"><button onClick={() => setDate(addDays(date, view === "day" ? -1 : view === "week" ? -7 : -30))} className="flex h-10 w-10 items-center justify-center rounded-xl border border-line text-zinc-500 hover:text-white"><ChevronLeft size={18} /></button><span className="min-w-48 text-center text-sm font-semibold">{view === "day" ? formatLongDate(date) : view === "week" ? `${formatShortDate(data.week.start)} — ${formatShortDate(data.week.end)}` : new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`))}</span><button onClick={() => setDate(addDays(date, view === "day" ? 1 : view === "week" ? 7 : 30))} className="flex h-10 w-10 items-center justify-center rounded-xl border border-line text-zinc-500 hover:text-white"><ChevronRight size={18} /></button></div></div>

    {view === "day" && <><section className="mb-5 grid gap-px overflow-hidden rounded-2xl border border-line bg-line md:grid-cols-3"><div className="bg-panel p-5 md:p-6"><p className="eyebrow">Total intake</p><p className="mt-3 font-display text-4xl font-bold tracking-[-.05em]">{data.today.total.toLocaleString()} <span className="text-sm text-acid">kcal</span></p></div><div className="bg-panel p-5 md:p-6"><p className="eyebrow">Meals logged</p><p className="mt-3 font-display text-4xl font-bold">{data.today.meals}</p></div><div className="bg-panel p-5 md:p-6"><p className="eyebrow">Sweet treats</p><p className="mt-3 font-display text-4xl font-bold text-coral">{data.today.desserts}</p></div></section>
      <section className="mb-5 grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><Card className="p-5 md:p-6"><p className="eyebrow">By meal</p><div className="mt-4 divide-y divide-line">{data.today.byMeal.map((meal) => <div key={meal.type} className="flex items-center justify-between py-4"><span className="flex items-center gap-3 text-sm"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/[.04]"><Utensils size={15} className="text-zinc-500" /></span>{mealLabels[meal.type]}</span><span className="font-display font-bold">{meal.calories.toLocaleString()} <b className="text-[10px] text-zinc-600">kcal</b></span></div>)}</div></Card><Card className="p-5 md:p-6"><div className="flex items-center justify-between"><p className="eyebrow">Meal log</p><span className="text-xs text-zinc-600">{data.today.entries.length} records</span></div>{data.today.entries.length ? <div className="mt-3 divide-y divide-line">{data.today.entries.map((entry) => <div key={entry.id} className="flex items-center gap-3 py-4"><span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-xl", entry.isDessert ? "bg-coral/10 text-coral" : "bg-acid/10 text-acid")}>{entry.isDessert ? <Candy size={17} /> : <Apple size={17} />}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{entry.mealName}</p><p className="mt-1 text-xs text-zinc-600">{entry.entryTime} · {mealLabels[entry.mealType]}</p></div><p className="shrink-0 font-display text-sm font-bold">{entry.confirmedCalories} <span className="text-[9px] text-zinc-600">kcal</span></p><button aria-label="Edit meal" onClick={() => void requireAdmin(() => { setDraft(entryToDraft(entry)); setEntryOpen(true); })} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-zinc-600 hover:bg-white/5 hover:text-white"><Edit3 size={16} /></button><button aria-label="Delete meal" onClick={() => void deleteMeal(entry)} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-zinc-600 hover:bg-coral/10 hover:text-coral"><Trash2 size={16} /></button></div>)}</div> : <div className="flex min-h-64 flex-col items-center justify-center text-center"><Camera className="mb-3 text-zinc-700" /><p className="text-sm font-semibold">No meals recorded</p><p className="mt-1 text-xs text-zinc-600">Unrecorded does not mean 0 kcal.</p></div>}</Card></section></>}
    {view === "week" && <PeriodChart period={data.week} compact />}
    {view === "month" && <PeriodChart period={data.month} />}

    <Card className="mt-5 p-5 md:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-coral/10 text-coral"><Cigarette size={18} /></span><div><h2 className="font-display font-bold">Life record</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Logging helps you notice patterns without judgment. Each record adjusts all life directions once.</p></div></div><Button variant="secondary" onClick={() => void logSmoking()}><Plus size={16} />Record one smoking event</Button></div>{data.smokingEntries.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{data.smokingEntries.slice(0, 8).map((entry) => <span key={entry.id} className="inline-flex items-center gap-2 rounded-xl border border-line px-3 py-2 text-xs text-zinc-400"><Clock3 size={13} />{formatShortDate(entry.entryDate)} · {entry.entryTime}<button onClick={() => void deleteSmokingEntry(entry)} aria-label="Delete smoking record" className="ml-1 text-zinc-600 hover:text-coral"><X size={14} /></button></span>)}</div>}</Card>

    <EntryDialog draft={draft} setDraft={setDraft} open={entryOpen} onOpenChange={setEntryOpen} onSave={() => void saveEntry()} busy={saving} />
    <AnalysisDialog open={analysisOpen} setOpen={(value) => { setAnalysisOpen(value); if (!value && preview) { URL.revokeObjectURL(preview); setPreview(null); } }} preview={preview} analysis={analysis} analyzing={analyzing} error={analysisError} draft={draft} setDraft={setDraft} onSave={() => void saveEntry()} busy={saving} onNewFile={(file) => void beginAnalysis(file)} />
  </div>;
}
